const points = [{ name: "Ansible / AWX", ring: "Adopt", quadrant: "Tools", moved: 0 },
{ name: "Argo CD", ring: "Adopt", quadrant: "Tools", moved: 0 },
{ name: "Argo Workflows", ring: "Assess", quadrant: "Tools", moved: 1 },
{ name: "GCP Artifact Registry", ring: "Adopt", quadrant: "Tools", moved: 0 },
{ name: "GCP Cloud Logging", ring: "Adopt", quadrant: "Tools", moved: 0 },
{ name: "GCP Cloud Monitoring", ring: "Adopt", quadrant: "Tools", moved: 0 },
{ name: "GCP Cloud Profiler", ring: "adpot", quadrant: "tools", moved: 0 },
{ name: "GCP Cloud Trace", ring: "Adopt", quadrant: "Tools", moved: 0 },
{ name: "GCP Container Registry", ring: "Hold", quadrant: "Tools", moved: 0 },
{ name: "Git", ring: "Adopt", quadrant: "Tools", moved: 0 },
{ name: "GitLab", ring: "Adopt", quadrant: "Tools", moved: 0 },
{ name: "GitLab CI", ring: "Adopt", quadrant: "Tools", moved: 0 },
{ name: "Grafana", ring: "Adopt", quadrant: "Tools", moved: 0 },
{ name: "Graphite", ring: "Hold", quadrant: "Tools", moved: 0 },
{ name: "Sentry", ring: "Adopt", quadrant: "Tools", moved: 0 },
{ name: "Statsd", ring: "Hold", quadrant: "Tools", moved: 0 },
{ name: "Hashicorp Terraform", ring: "Adopt", quadrant: "Tools", moved: 0 },
{ name: "Lighthouse CI", ring: "Adopt", quadrant: "Tools", moved: 0 },
{ name: "Transifex", ring: "Adopt", quadrant: "Tools", moved: 0 },
{ name: "nvm", ring: "Adopt", quadrant: "Tools", moved: 0 },
{ name: "yarn", ring: "Adopt", quadrant: "Tools", moved: 0 },
{ name: "poetry ", ring: "Adopt", quadrant: "Tools", moved: 1 },
{ name: "pipenv", ring: "Hold", quadrant: "Tools", moved: 0 },
{ name: "Fabric", ring: "Adopt", quadrant: "Tools", moved: 0 },
{ name: "Sphinx", ring: "Adopt", quadrant: "Tools", moved: 0 },
{ name: "JWT", ring: "Adopt", quadrant: "Tools", moved: 0 },
{ name: "mypy", ring: "Adopt", quadrant: "Tools", moved: 1 },
{ name: "flake8", ring: "Adopt", quadrant: "Tools", moved: 0 },
{ name: "k6", ring: "Adopt", quadrant: "Tools", moved: 1 },
{ name: "Renovate Bot", ring: "Trial", quadrant: "Tools", moved: 1 },
{ name: "Apache", ring: "Hold", quadrant: "Infrastructure & Platforms", moved: 0 },
{ name: "Beanstalk", ring: "Hold", quadrant: "Infrastructure & Platforms", moved: 0 },
{ name: "Celery", ring: "Adopt", quadrant: "Infrastructure & Platforms", moved: 0 },
{ name: "Cloudflare", ring: "Adopt", quadrant: "Infrastructure & Platforms", moved: 0 },
{ name: "Docker", ring: "Adopt", quadrant: "Infrastructure & Platforms", moved: 0 },
{ name: "Elasticsearch", ring: "Adopt", quadrant: "Infrastructure & Platforms", moved: 0 },
{ name: "GCP Big Query", ring: "Adopt", quadrant: "Infrastructure & Platforms", moved: 0 },
{ name: "GCP Cloud DNS", ring: "Adopt", quadrant: "Infrastructure & Platforms", moved: 0 },
{ name: "GCP Cloud Functions", ring: "Trial", quadrant: "Infrastructure & Platforms", moved: 1 },
{ name: "GCP Cloud Run", ring: "Assess", quadrant: "Infrastructure & Platforms", moved: 1 },
{ name: "GCP Cloud SQL MySQL", ring: "Adopt", quadrant: "Infrastructure & Platforms", moved: 0 },
{ name: "GCP Cloud SQL PostgreSQL", ring: "Adopt", quadrant: "Infrastructure & Platforms", moved: 0 },
{ name: "GCP Cloud Scheduler", ring: "Trial", quadrant: "Infrastructure & Platforms", moved: 1 },
{ name: "GCP Cloud Storage", ring: "Adopt", quadrant: "Infrastructure & Platforms", moved: 0 },
{ name: "GCP Compute Engine", ring: "Adopt", quadrant: "Infrastructure & Platforms", moved: 0 },
{ name: "GCP Firebase", ring: "Adopt", quadrant: "Infrastructure & Platforms", moved: 0 },
{ name: "GCP Datastore / Firestore", ring: "Adopt", quadrant: "Infrastructure & Platforms", moved: 0 },
{ name: "GCP Kubernetes Engine", ring: "Adopt", quadrant: "Infrastructure & Platforms", moved: 0 },
{ name: "GCP Load Balancing", ring: "Adopt", quadrant: "Infrastructure & Platforms", moved: 0 },
{ name: "GCP Memorystore Redis", ring: "Adopt", quadrant: "Infrastructure & Platforms", moved: 0 },
{ name: "GCP Pub/Sub", ring: "Adopt", quadrant: "Infrastructure & Platforms", moved: 0 },
{ name: "GCP Vertex AI", ring: "Adopt", quadrant: "Infrastructure & Platforms", moved: 1 },
{ name: "Keycloak", ring: "Adopt", quadrant: "Infrastructure & Platforms", moved: 0 },
{ name: "KVM", ring: "Hold", quadrant: "Infrastructure & Platforms", moved: 0 },
{ name: "Mandrill", ring: "Hold", quadrant: "Infrastructure & Platforms", moved: 0 },
{ name: "Nginx", ring: "Adopt", quadrant: "Infrastructure & Platforms", moved: 0 },
{ name: "OpenVPN Cloud", ring: "Adopt", quadrant: "Infrastructure & Platforms", moved: 1 },
{ name: "Percona MongoDB", ring: "Hold", quadrant: "Infrastructure & Platforms", moved: 0 },
{ name: "Percona MySQL", ring: "Hold", quadrant: "Infrastructure & Platforms", moved: 0 },
{ name: "Postfix", ring: "Adopt", quadrant: "Infrastructure & Platforms", moved: 0 },
{ name: "c", ring: "Hold", quadrant: "Infrastructure & Platforms", moved: 0 },
{ name: "SendGrid", ring: "Adopt", quadrant: "Infrastructure & Platforms", moved: 0 },
{ name: "Sophos Firewall", ring: "Adopt", quadrant: "Infrastructure & Platforms", moved: 0 },
{ name: "Solr", ring: "Adopt", quadrant: "Infrastructure & Platforms", moved: 0 },
{ name: "Hashicorp Vault", ring: "Adopt", quadrant: "Infrastructure & Platforms", moved: 0 },
{ name: "Airflow", ring: "Adopt", quadrant: "Infrastructure & Platforms", moved: 0 },
{ name: "Microsoft SQL Server", ring: "Hold", quadrant: "Infrastructure & Platforms", moved: 0 },
{ name: "Python", ring: "Adopt", quadrant: "Languages & Frameworks", moved: 0 },
{ name: "PHP", ring: "Adopt", quadrant: "Languages & Frameworks", moved: 0 },
{ name: "TypeScript", ring: "Adopt", quadrant: "Languages & Frameworks", moved: 0 },
{ name: "JavaScript", ring: "Adopt", quadrant: "Languages & Frameworks", moved: 0 },
{ name: "golang", ring: "Assess", quadrant: "Languages & Frameworks", moved: 1 },
{ name: "Django", ring: "Adopt", quadrant: "Languages & Frameworks", moved: 0 },
{ name: "Django rest framework", ring: "Adopt", quadrant: "Languages & Frameworks", moved: 0 },
{ name: "Node", ring: "Adopt", quadrant: "Languages & Frameworks", moved: 0 },
{ name: "React", ring: "Adopt", quadrant: "Languages & Frameworks", moved: 0 },
{ name: "SASS", ring: "Adopt", quadrant: "Languages & Frameworks", moved: 0 },
{ name: "Tailwind CSS", ring: "Adopt", quadrant: "Languages & Frameworks", moved: 1 },
{ name: "Storybook", ring: "Adopt", quadrant: "Languages & Frameworks", moved: 0 },
{ name: "jQuery", ring: "Hold", quadrant: "Languages & Frameworks", moved: 0 },
{ name: "bash", ring: "Adopt", quadrant: "Languages & Frameworks", moved: 0 },
{ name: "Flask ", ring: "Adopt", quadrant: "Languages & Frameworks", moved: 0 },
{ name: "fastAPI", ring: "Adopt", quadrant: "Languages & Frameworks", moved: 1 },
{ name: "Selenium webdriver", ring: "Adopt", quadrant: "Languages & Frameworks", moved: 0 },
{ name: "pytest", ring: "Adopt", quadrant: "Languages & Frameworks", moved: 0 },
{ name: "CoffeeScript", ring: "Hold", quadrant: "Languages & Frameworks", moved: 0 },
{ name: "Vue.JS", ring: "Hold", quadrant: "Languages & Frameworks", moved: 1 },
{ name: "Ember.js", ring: "Hold", quadrant: "Languages & Frameworks", moved: 0 },
{ name: "sqlalchemy", ring: "Adopt", quadrant: "Languages & Frameworks", moved: 1 },
{ name: "alembic", ring: "Adopt", quadrant: "Languages & Frameworks", moved: 1 },
{ name: "pinject", ring: "Adopt", quadrant: "Languages & Frameworks", moved: 1 },
{ name: "Zero Trust", ring: "Assess", quadrant: "Techniques", moved: 0 },
{ name: "GitOps", ring: "Adopt", quadrant: "Techniques", moved: 0 },
{ name: "Scrum", ring: "Adopt", quadrant: "Techniques", moved: 0 },
{ name: "Code review", ring: "Adopt", quadrant: "Techniques", moved: 0 },
{ name: "TDD", ring: "Adopt", quadrant: "Techniques", moved: 0 },
{ name: "Peer programming", ring: "Adopt", quadrant: "Techniques", moved: 0 },
{ name: "Clean Architecture / DDD", ring: "Adopt", quadrant: "Techniques", moved: 0 },
]