name: Rebuild points and publish 
on: [push, workflow_dispatch]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
       - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
       - name: Check out repository code
         uses: actions/checkout@v3
         with:
          fetch-depth: 0
          ref: main
       - run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."
       - name: Refresh points.js and push it     
         env:
          GOOGLE_KEY: ${{ secrets.GOOGLE_KEY }}
         run: |
          cd bin && npm install && node refresh.js "$GOOGLE_KEY" && more ../points.js
       - name: Add & Commit
         uses: EndBug/add-and-commit@v9.0.0
       - run: echo "This job's status is ${{ job.status }}."   
